compute_environment: LOCAL_MACHINE
mixed_precision: 'fp16'
num_processes: 1
num_machines: 1
machine_rank: 0
distributed_type: 'NO'
main_process_ip: null
main_process_port: null
main_training_function: null
use_cpu: false
